#!/usr/bin/env node
/**
 * Regenerate src/app/tokens.css from a brand tokens JSON file.
 *
 *   npm run brand:apply -- ../brand/tokens.json
 *   node scripts/apply-brand.mjs <tokens.json> [--out <file>] [--strict]
 *
 * The JSON shape is documented in brand/tokens.example.json. Input is validated and the
 * script fails with a clear message listing every problem. Colour pairs that fall below
 * WCAG AA (4.5:1) are reported as warnings, or as errors with --strict.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const COLOR_KEYS = [
  "brand",
  "brand-foreground",
  "accent",
  "accent-foreground",
  "background",
  "foreground",
  "muted",
  "muted-foreground",
  "border",
  "card",
  "card-foreground",
];

export const MODES = ["light", "dark"];

/** [foreground, background] pairs that must reach WCAG AA for normal text. */
export const CONTRAST_PAIRS = [
  ["foreground", "background"],
  ["card-foreground", "card"],
  ["muted-foreground", "background"],
  ["muted-foreground", "muted"],
  ["muted-foreground", "card"],
  ["brand-foreground", "brand"],
  ["accent-foreground", "accent"],
  ["brand", "background"],
  ["accent", "background"],
];

export const MIN_CONTRAST = 4.5;

const HEX = /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;
const FONT_STACK = /^[A-Za-z0-9 ,"'._-]+$/;
const RADIUS = /^(?:\d+|\d*\.\d+)(?:rem|em|px)$/;

export class BrandTokensError extends Error {
  /** @param {string[]} problems */
  constructor(problems) {
    super(`Invalid brand tokens:\n${problems.map((p) => `  - ${p}`).join("\n")}`);
    this.name = "BrandTokensError";
    this.problems = problems;
  }
}

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeHex(hex) {
  const lower = hex.toLowerCase();
  return lower.length === 4
    ? `#${lower[1]}${lower[1]}${lower[2]}${lower[2]}${lower[3]}${lower[3]}`
    : lower;
}

/**
 * Validate and normalise a parsed tokens object.
 * @param {unknown} input
 * @returns {{ color: { light: Record<string,string>, dark: Record<string,string> }, font: { sans: string, display: string }, radius: string }}
 */
export function parseTokens(input) {
  const problems = [];
  if (!isRecord(input))
    throw new BrandTokensError(["the file must contain a JSON object"]);

  const color = { light: {}, dark: {} };
  if (!isRecord(input.color)) {
    problems.push('missing "color" object with "light" and "dark" palettes');
  } else {
    for (const mode of MODES) {
      const palette = input.color[mode];
      if (!isRecord(palette)) {
        problems.push(`missing "color.${mode}" palette`);
        continue;
      }
      for (const key of COLOR_KEYS) {
        const value = palette[key];
        if (value === undefined) {
          problems.push(`missing "color.${mode}.${key}"`);
        } else if (typeof value !== "string" || !HEX.test(value)) {
          problems.push(
            `"color.${mode}.${key}" must be a hex colour like #1a2b3c or #abc (got ${JSON.stringify(value)})`,
          );
        } else {
          color[mode][key] = normalizeHex(value);
        }
      }
    }
  }

  const font = { sans: "", display: "" };
  if (!isRecord(input.font)) {
    problems.push('missing "font" object with "sans" and "display" font stacks');
  } else {
    for (const key of ["sans", "display"]) {
      const value = input.font[key];
      if (value === undefined) problems.push(`missing "font.${key}"`);
      else if (typeof value !== "string" || !FONT_STACK.test(value.trim())) {
        problems.push(
          `"font.${key}" must be a CSS font stack using only letters, digits, spaces, commas, quotes, dots, hyphens and underscores (got ${JSON.stringify(value)})`,
        );
      } else font[key] = value.trim();
    }
  }

  let radius = "";
  if (input.radius === undefined) problems.push('missing "radius" (e.g. "0.75rem")');
  else if (typeof input.radius !== "string" || !RADIUS.test(input.radius.trim())) {
    problems.push(
      `"radius" must be a length in rem, em or px, e.g. "0.75rem" (got ${JSON.stringify(input.radius)})`,
    );
  } else radius = input.radius.trim();

  if (problems.length > 0) throw new BrandTokensError(problems);
  return { color, font, radius };
}

/** Render the contents of tokens.css. Output is deterministic. */
export function renderTokensCss(tokens) {
  const colorLines = (mode, indent) =>
    COLOR_KEYS.map((key) => `${indent}--${key}: ${tokens.color[mode][key]};`).join("\n");

  return `/*
 * Brand design tokens.
 * Generated by scripts/apply-brand.mjs from brand/tokens.json. Do not edit by hand:
 *   npm run brand:apply -- <path/to/tokens.json>
 * Consumed by the Tailwind @theme block in globals.css.
 */
:root {
  color-scheme: light dark;
${colorLines("light", "  ")}
  --font-sans: ${tokens.font.sans};
  --font-display: ${tokens.font.display};
  --radius: ${tokens.radius};
}

@media (prefers-color-scheme: dark) {
  :root {
${colorLines("dark", "    ")}
  }
}
`;
}

function channel(value) {
  const c = value / 255;
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}

/** Relative luminance of a #rrggbb colour (WCAG 2.x). */
export function luminance(hex) {
  const full = normalizeHex(hex);
  const [r, g, b] = [1, 3, 5].map((i) => Number.parseInt(full.slice(i, i + 2), 16));
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

/** WCAG contrast ratio between two colours (1 to 21). */
export function contrastRatio(a, b) {
  const [light, dark] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (light + 0.05) / (dark + 0.05);
}

/** Pairs below WCAG AA for normal text, per mode. Empty means the palette passes. */
export function checkContrast(tokens, minimum = MIN_CONTRAST) {
  const failures = [];
  for (const mode of MODES) {
    for (const [foreground, background] of CONTRAST_PAIRS) {
      const ratio = contrastRatio(
        tokens.color[mode][foreground],
        tokens.color[mode][background],
      );
      if (ratio < minimum) {
        failures.push({
          mode,
          foreground,
          background,
          ratio: Math.round(ratio * 100) / 100,
          minimum,
        });
      }
    }
  }
  return failures;
}

const USAGE = `Usage: node scripts/apply-brand.mjs <tokens.json> [--out <file>] [--strict]

Regenerates src/app/tokens.css from a brand tokens file (shape: brand/tokens.example.json).
  --out <file>  write somewhere else (default: src/app/tokens.css)
  --strict      treat WCAG AA contrast warnings as errors`;

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/**
 * CLI entry point. Returns the process exit code instead of exiting, so it is testable.
 * @param {string[]} argv arguments after the script name
 * @param {{ cwd?: string, stdout?: (s: string) => void, stderr?: (s: string) => void }} [io]
 */
export function run(argv, io = {}) {
  const cwd = io.cwd ?? process.cwd();
  const stdout = io.stdout ?? ((s) => process.stdout.write(`${s}\n`));
  const stderr = io.stderr ?? ((s) => process.stderr.write(`${s}\n`));

  let input;
  let out = path.join(projectRoot, "src", "app", "tokens.css");
  let strict = false;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--help" || arg === "-h") {
      stdout(USAGE);
      return 0;
    }
    if (arg === "--strict") strict = true;
    else if (arg === "--out") {
      const value = argv[i + 1];
      if (!value) {
        stderr(`--out needs a file path\n${USAGE}`);
        return 2;
      }
      i += 1;
      out = path.resolve(cwd, value);
    } else if (arg?.startsWith("-")) {
      stderr(`Unknown option ${arg}\n${USAGE}`);
      return 2;
    } else if (input === undefined) input = arg;
    else {
      stderr(`Unexpected argument ${arg}\n${USAGE}`);
      return 2;
    }
  }
  if (!input) {
    stderr(USAGE);
    return 2;
  }

  const file = path.resolve(cwd, input);
  let raw;
  try {
    raw = readFileSync(file, "utf8");
  } catch (error) {
    stderr(`Cannot read ${file}: ${error.message}`);
    return 1;
  }

  let json;
  try {
    json = JSON.parse(raw);
  } catch (error) {
    stderr(`${file} is not valid JSON: ${error.message}`);
    return 1;
  }

  let tokens;
  try {
    tokens = parseTokens(json);
  } catch (error) {
    if (error instanceof BrandTokensError) {
      stderr(
        `${file}\n${error.message}\nSee brand/tokens.example.json for the expected shape.`,
      );
      return 1;
    }
    throw error;
  }

  const failures = checkContrast(tokens);
  for (const f of failures) {
    stderr(
      `${strict ? "error" : "warning"}: ${f.mode} ${f.foreground} on ${f.background} has contrast ${f.ratio}:1 (WCAG AA needs ${f.minimum}:1)`,
    );
  }
  if (strict && failures.length > 0) return 1;

  mkdirSync(path.dirname(out), { recursive: true });
  writeFileSync(out, renderTokensCss(tokens));
  stdout(`Wrote ${path.relative(cwd, out) || out}`);
  return 0;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
) {
  process.exitCode = run(process.argv.slice(2));
}
